### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Enmaboya** [ebess/advanced-nova-media-library#1]
hi!
![default](https://user-images.githubusercontent.com/32259003/46320209-51333980-c5ee-11e8-9fdc-e2697c39db05.png)
1) "Media Media"
is a media model or
Kingsley \ NovaMediaLibrary \ Resources \ Media?

2) I have models "Album" and "Photo", the relationship "one to many."
can this package save a photo for this connection?
![default](https://user-images.githubusercontent.com/32259003/46320412-52b13180-c5ef-11e8-9978-a250d2435dfa.png)

**Comment by ebess** [comment]
Hi @Enmaboya 
I'm not sure you are really using the https://github.com/spatie/laravel-medialibrary
The Media object should be a `Spatie\MediaLibrary\Models\Media` instance. The `registerMediaConversions` is straight from the [spatie media lib docs](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions).

**Comment by ebess** [comment]
i'll close this issue, your PR has been merged already adressing this issue.
