### ISSUE TITLE
Question - How can i store in driver with not public visibility

### ISSUE THREAD

**Issue by Yannik-Slym** [ebess/advanced-nova-media-library#101]
Hello,

I would like to store my media in a driver with no public visibility.

Example :
```
 'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
```

But when i try to display my ressource, the link does'nt work, normal there is not public visibility but the form is not available :/

But any idea how deal with it ? 

I think about disable the preview on form view ( i can do that at now ) and add link manually with  "displayUsing" on index en detail view.

Thanks ;)

**Comment by ebess** [comment]
Hi @Yannik-Slym Take a look right here: https://docs.spatie.be/laravel-medialibrary/v7/downloading-media/downloading-a-single-file/

I think you need to handle the "privacy" yourself. Create a controller similar to the download controller stated above. You will need also to create a custom url generator: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/generating-custom-urls/#generating-custom-urls

Not an issue of this package, imo.

**Comment by Yannik-Slym** [comment]
Thanks ;)
