### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by GarethSomers** [ebess/advanced-nova-media-library#110]
Can't see much activity from @ebess from about May onwards

**Comment by chrispage1** [comment]
I was wondering that - perhaps needs a fork!

**Comment by GarethSomers** [comment]
Hi @ebess thanks for the reply. I absolutely understand, it's your own time you're putting into this project and I greatly appreciate what you've done so far.

I think as a priority what myself and @chrispage1 are hoping for is this PR https://github.com/ebess/advanced-nova-media-library/pull/107 to be merged in.

You'll also see my comment on that PR about merging in this commit aswell from my unrelated PR https://github.com/ebess/advanced-nova-media-library/commit/6755ff812be388c96dfacffc76abf39078eb6ace

These combined provide better compatibility with the `whitecube/nova-flexible-content` package.

I'd be happy to review and approve these code reviews in the short term.

**Comment by ebess** [comment]
@GarethSomers I'll try to designate some time to the issues on this package starting by tomorrow 1-2 hours. I will take a look in the PRs first. Thank you for PRs!

**Comment by GarethSomers** [comment]
Hi @ebess sorry to bother you again, is this project being maintained?
