### ISSUE TITLE
Can't update Laravel to 6.0

### ISSUE THREAD

**Issue by RespectPick** [ebess/advanced-nova-media-library#111]
composer.json
```
"ebess/advanced-nova-media-library": "^2.8",
"laravel/framework": "^6.0",
```

>   Problem 1
>     - Installation request for ebess/advanced-nova-media-library ^2.8 -> satisfiable by ebess/advanced-nova-media-library[2.8.0].
>     - Conclusion: don't install laravel/framework v6.0.0
>     - Conclusion: don't install laravel/framework 6.x-dev
>     - ebess/advanced-nova-media-library 2.8.0 requires laravel/framework ^5.6 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
>     - Can only install one of: laravel/framework[6.0.x-dev, 5.6.x-dev].
>     - Can only install one of: laravel/framework[6.0.x-dev, 5.7.x-dev].
>     - Can only install one of: laravel/framework[6.0.x-dev, 5.8.x-dev].
>     - Installation request for laravel/framework ^6.0 -> satisfiable by laravel/framework[6.0.x-dev, 6.x-dev, v6.0.0].
>

**Comment by nemrutco** [comment]
I did a pull request but didn't do any test. #113

**Comment by ragingdave** [comment]
That and laravel 6.0 only supports 7.2 and up so not sure if anything else would break in here.

**Comment by RespectPick** [comment]
@ragingdave so when will this happen?

**Comment by ragingdave** [comment]
Oh didn't realize I was marked as a contributor....umm I don't know. I do use this package, but I don't maintain it. I am trying to get my own project running on L6.0 and am running into at least 5 packages (both internal and open-source) that are running into this same issue. I'm basically trying to help where I can with PRs that can get things installable/fixing if the fixes are small enough in my free time.

**Comment by nemrutco** [comment]
I just corrected my #114 pull request. Should be ok after marge.

**Comment by ebess** [comment]
Hi, I need to test it. If it works on L6, I will merge the PR.

**Comment by charlielangridge** [comment]
@ebess  any update on this?

**Comment by ebess** [comment]
https://github.com/ebess/advanced-nova-media-library/releases/tag/2.9.1 released!

**Comment by aaronmeder** [comment]
Thanks guys! 👍
