### ISSUE TITLE
Single Image upload, Documentation unclear or outdated

### ISSUE THREAD

**Issue by marky291** [ebess/advanced-nova-media-library#117]
Documentation example code does not match the image, instead you are free to add as many uploads as you want.

<img width="720" alt="Screenshot 2019-09-04 at 20 45 45" src="https://user-images.githubusercontent.com/5384515/64286260-097f0580-cf55-11e9-8a71-8c780a50b59c.png">
<img width="780" alt="Screenshot 2019-09-04 at 20 45 41" src="https://user-images.githubusercontent.com/5384515/64286261-0a179c00-cf55-11e9-94fa-42d4d973b72d.png">
<img width="930" alt="Screenshot 2019-09-04 at 20 45 20" src="https://user-images.githubusercontent.com/5384515/64286262-0a179c00-cf55-11e9-8881-baf330e250e3.png">

**Comment by ebess** [comment]
Hi @marky291 Did you set https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#single-file-collections on your collection?

**Comment by marky291** [comment]
This was not mention on the github, single file uploads, I will try this thanks.
