### ISSUE TITLE
Trix Integration

### ISSUE THREAD

**Issue by nickpoulos** [ebess/advanced-nova-media-library#12]
Great work on this package, very useful and cool.

This is clearly in the realm of enhancement, but it would be amazing to be able to drag an Image from the field to be inserted Nova Trix field.  Not quite sure if this would be an enhancement to this package, extending the Nova Trix field or a combination of both.

**Comment by ebess** [comment]
Hi, I'm not really sure trix should be a concern of this package. Does trix support drag and drop of images displayed on the page? If so, it should be enough to remove the preview overlay on the thumbnail images. Also, you would drop the thumbnail image into trix...

**Comment by shirshak55** [comment]
yes i also think trix is not suitable here.

**Comment by nickpoulos** [comment]
> Hi, I'm not really sure trix should be a concern of this package. Does trix support drag and drop of images displayed on the page? If so, it should be enough to remove the preview overlay on the thumbnail images. Also, you would drop the thumbnail image into trix...

Thanks for your input. Trix is not a concern of this package I suppose that is true.  The reason I was suggesting is because Trix is the default Laravel Nova rich text field, and it would be great to set a flag/method/config item that would allow this package to work with a rich text field out of the box.  

Trix DOES support image/drag drop but I do not think from images on the page, only a file drop, since it handles the upload itself and then stores in its own trix_attachments table, which kind of clashes with this package/library.  So when building a post or any other model that has both images and rich text, there is no nice way to use them together.  

Like I said in my first post, I was not 100% sure where the modifications might be, so I might just have to extend the original Nova Trix field and see if I can modify it to handle <img> drops instead of just file. 👍Maybe no changes on this package needed.

**Comment by shirshak55** [comment]
@nickpoulos  did u came up with any solution?

I would blame Laravel Nova for not making design of trix. 

See this : https://nova.laravel.com/docs/3.0/resources/fields.html#Trix-File-Uploads

They expect to create two tables "nova_pending_trix_attachments" and "nova_trix_attachments".

I am thinking of creating the own version of Trix and hooking up to laravel media library. So this package should update automatically.

**Comment by jberculo** [comment]
Did you follow up on that idea @shirshak55 ? How did you solve it?

**Comment by shirshak55** [comment]
@jberculo i created the two table and it was fairly easy to solve. I followed similar approach trix handle the upload.
