### ISSUE TITLE
Unable to upload files in edge

### ISSUE THREAD

**Issue by xuneXTW** [ebess/advanced-nova-media-library#120]
Hi there,

I am unable to upload files in edge, the console throws always this error:
![image](https://user-images.githubusercontent.com/26743261/65167446-dce1e800-da42-11e9-8a9f-900c5fa42252.png)

Library Version is 2.9.1

**Comment by DecortDev** [comment]
Same error

<img width="571" alt="Bildschirmfoto 2019-10-11 um 13 45 33" src="https://user-images.githubusercontent.com/41015675/66649082-888aec00-ec2d-11e9-8fc6-c39c39f55da9.png">

`"version": "2.9.1"`
