### ISSUE TITLE
Missing multiple filesystem in documentation

### ISSUE THREAD

**Issue by LorenzoSapora** [ebess/advanced-nova-media-library#121]
I cannot seem to use another filesystem, and the documentation doesn't contain any hints. The original documentation mentions that it's just an additional argument that's passed to `>toMediaCollection('images', 'aws')` [spatie docs](https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/working-with-multiple-filesystems/).

I'm a little confused as to where to put that, as in the model we only use `addMediaConversion` and `addMediaCollection`, and the resource nova resource doesn't allow a `->toMediaCollection`

Probably spacing on this, because I can't see anyone else hitting this issue here, or anywhere else.

Happy to PR to the documentation when you've pointed me to the obvious.

Nova: 2.3.1
Laravel: 5.8~
This package: `"ebess/advanced-nova-media-library": "^2.9",`

**Comment by LorenzoSapora** [comment]
Update: I changed the default value in the config

```php
// config/medialibrary.php
return [

    /*
     * The disk on which to store added files and derived images by default. Choose
     * one or more of the disks you've configured in config/filesystems.php.
     */
    'disk_name' => 'gcs',

//...
];
```

But I'm still stumped on how to choose between filesystems, if I were to create an array for `disk_name` something like this

```php
'disk_name' => ['gcs'. 'local', 'aws'],
```

**Comment by ebess** [comment]
Hey @LorenzoSapora I don't get it. What are you trying to achieve here? You want to upload to the same media collection but to different disk on different fields in nova? Something like this?

If you want your files to be stored in multiple disks / filesystems, you should try to use the replica driver of the flysystem. This package is not related to this, tho.

**Comment by LorenzoSapora** [comment]
I worked it out today, and was going to close this earlier, but am still curious about some functionality.

My confusion was around disks in the model. I was testing with two different names, and not understanding why. Fix now, but I am still a little confused as to how to use multiple disks.

For example:

```php
// app/Models/User
namespace App\Models;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Illuminate\Database\Eloquent\Model;

class Game extends Model implements HasMedia
{
    use Searchable;
    use HasMediaTrait;
    use FiltersRecords;

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(130)
            ->height(130);
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('cover_image', 'public')->singleFile();
        $this->addMediaCollection('screenshots', 'gcs');
    }

// [...]

];
```

```php
// config/medialibrary.php
return [
    'disk_name' => ['gcs', 'public'],

// [...]
];
```

Doesn't seem to work. I can upload to gcs (my own urlgenerator), but not to public. whereas if I specific only public in disk_name, I can upload to public. I am almost definitely misreading something somewhere.

**Comment by ebess** [comment]
As I told, to upload to multiple filesystem I'd suggest to use the [replicate adapter](https://flysystem.thephpleague.com/docs/adapter/replicate/). Additional docs / help for the laravel media library you can find in the spatie docs / repository. This package is only the integration for laravel nova.

**Comment by LorenzoSapora** [comment]
I didn't mean replication. For example, avatars stored locally, and user images stored on AWS. But as you said, I believe this is a `spatie/laravel-medialibrary`issue, as `disk_name` allows strings, not arrays.

**Comment by martinlanglois** [comment]
Unsure if you are pointing out the same issue i am having....  
But basically, i am having this issue where even tho I can upload to different disks. 
( example publicly available s3 bucket, vs.  private s3 bucket ) 

the field will only return URLs based of the default disk... so I end up with a broken link :( 

in medialib..php
`
'disk_name' => 's3-private', // this is our bucket where files are hidden

`

in my Nova resource 
`Images::make('Cover Picture', 'cover_picture'),`

in my model 
`public function registerMediaCollections()
    {
        $this->addMediaCollection('cover_picture')
            ->singleFile()
            ->useDisk('s3-public-files');  // different then default
    }

    public function setCoverPictureAttribute($file)
    {
        $this->addMedia($file)->toMediaCollection('cover_picture');
    }
`

The upload goes to the right bucket. 
however, when browsing **in nova** the links are pointing to the original bucket ( resulting in a broken link since it's private  ) 

I have tried adding a link to the medialib..php 
`
    's3-private' => [
        /*
         * The domain that should be prepended when generating urls.
         */
        'domain' => 'https://'.env('AWS_BUCKET').'.s3.amazonaws.com',
    ],
    's3-public-files' => [
        'domain' => 'https://'.env('AWS_BUCKET_PUBLIC').'.s3.amazonaws.com',
    ],
`

ps. there might be typos in the code since I have changed my settings to generic names.. 
but i insure you my names are matching in the code :P

**Comment by sunnydesign** [comment]
Hi guys!

I have a similar problem.
I need to separate production storage on S3 from local storage on local disc via `.env`.

For example, I have 2 discs in my config `filesystems.php`:

```
'media_local' => [
    'driver' => 'local',
    'root' => storage_path('app/public/media'),
    'url' => env('APP_URL').'/storage/media',
    'visibility' => 'public',
],

'media_s3' => [
    'driver' => 's3',
    'key' => env('DO_ACCESS_KEY_ID'),
    'secret' => env('DO_SECRET_ACCESS_KEY'),
    'region' => env('DO_DEFAULT_REGION'),
    'bucket' => env('DO_BUCKET'),
    'url' => env('DO_URL'),
    'endpoint' => env('DO_ENDPOINT'),
    'use_path_style_endpoint' => env('DO_USE_PATH_STYLE_ENDPOINT', false),
    'visibility' => 'public',
],
```
Also I have in the config `media-library.php`:

```
'disk_name' => env('MEDIA_DISK', 'media_local'),
```

In my production `.env` I want to use:
```
MEDIA_DISK=media_s3
```

But in my local `.env` I want to use:
```
MEDIA_DISK=media_local
```

After that I try to add in the config `nova-media-library.php`:

```
'disk_name' => env('MEDIA_DISK', 'media_local'),
```

But it doesn't work.

So, as a result, I can to configure disk in  the `media-library.php` but cannot to configure one in the `nova-media-library.php`.

How can I solve this problem?
