### ISSUE TITLE
Big files crash browser tab

### ISSUE THREAD

**Issue by Kturva** [ebess/advanced-nova-media-library#126]
Similarly to #68 the library outputs base64 strings of selected files to the DOM:
https://github.com/ebess/advanced-nova-media-library/blob/9f3f596cdfdfcd200234dcb373b9da917ea004eb/resources/js/components/SingleFile.vue#L4

When the file is a few hundred megs in size this crashes the tab at least on Firefox. 😅

**Comment by Kturva** [comment]
Looking at it again I also had to strip out this `FileReader` thing to be able use 800 meg files, browser doesn't want to load it all in memory: https://github.com/ebess/advanced-nova-media-library/blob/9f3f596cdfdfcd200234dcb373b9da917ea004eb/resources/js/components/Gallery.vue#L111-L129

**Comment by ebess** [comment]
#68 Is exactly the problem. One approach would be to resize the image via canvas. But you can continue discussion in #68
