### ISSUE TITLE
How To Add Image For Duplicate A Table Row

### ISSUE THREAD

**Issue by jahid56** [ebess/advanced-nova-media-library#127]
I am using this package for duplicate of a row
`https://packagist.org/packages/jackabox/nova-duplicate-field`

There Is Multiple Image attached with the table row, How can I Upload The Image with the duplication Of Field

**Comment by ebess** [comment]
Hi @jahid56 You need to hook into the `replicate` method of the model. Not related to this package, tho. https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files/#copymedia Maybe this will help you.
