### ISSUE TITLE
Non public path

### ISSUE THREAD

**Issue by cliffordjames** [ebess/advanced-nova-media-library#144]
How do I handle media to a non public path without getting the "Storage path X is not path of public path X" error after uploading?

**Comment by ebess** [comment]
hey @cliffordjames 
You can a public storage like shown here: https://laravel.com/docs/5.8/filesystem#the-public-disk
Currently there is no way to do that. But should be possible with temporary urls on S3 / signed urls for media, see: https://github.com/ebess/advanced-nova-media-library/issues/64
