### ISSUE TITLE
Nova 2.9.2 update

### ISSUE THREAD

**Issue by semchishinv** [ebess/advanced-nova-media-library#145]
Hi, thanks for your job!

Please, update it for new **Nova release(2.9.2)**
Installation request for ebess/advanced-nova-media-library ^2.9 -> satisfiable by ebess/advanced-nova-media-library[2.9.0, 2.9.1].

**Comment by ebess** [comment]
Hi @semchishinv I don't get it totally. the versioning on this package is not related the versioning on laravel/nova package. I just checkout out `2.9.1` on this package working on `2.9.3` on laravel/nova.
