### ISSUE TITLE
Download button in detail view not working properly when media table uses another connectiion.

### ISSUE THREAD

**Issue by newtongamajr** [ebess/advanced-nova-media-library#152]
I'm using hyn/multitenant to create a multi-tenant environment for my applications and my media table resides on another database connection. Everything is fine with other features of advanced-nova-media-library, but this specific access to media seems to be done directly to media table, instead of using Media model class, causing the following error:

["42S02",1146,"Table 'redditumdb.media' doesn't exist"],"sqlExec":"select * from `media` where `id` = ? limit 1","sqlBindings":["64"]}}
In this case, my media table is under 607585c0a06311e9bf656ba9c86393fd, not redditumdb, that's the system default schema. My media table is located on tenant schema for hyn/multitenant.

Best regards!
![Anotação 2020-02-25 115908](https://user-images.githubusercontent.com/8673343/75259157-576b1c80-57c6-11ea-85df-0e8dd2ac9d71.png)

**Comment by nlappe** [comment]
I can confirm this. My Nova is just mounting the DB of the actual Laravel App (which contains the Media Table), while the Nova default DB manages Admin users, meta data etc. and i have the exact same behavior. As i'm just using images that's half bad - the admins can still use the magnifying glass and download the opened image via right click. 

Some sort of configuration would be nice though - like a possibility to generate the URL yourself, turning off the download icon or using a custom Media Model. - at least i didn't find anything like that in the autocomplete or the docs.

Nova reported error below (accesses default DB where no media table resides):
![image](https://user-images.githubusercontent.com/8957782/79774952-ce8ae000-8333-11ea-949e-2129af685abb.png)

**Comment by bkintanar** [comment]
As a maintainer of both this package and https://github.com/tenancy/multi-tenant. I'll try to check on this when I have time.

Thanks for your effort in reporting this issue.

**Comment by nlappe** [comment]
@bkintanar Just to clearify and maybe make your life easier - i'm not using tenancy/multi-tenant. just plain Laravel/ Nova with multiple Databases and a custom Media Model (that extends the spatie Media Model and only overrides the $connection property to set the database connection).

i've been browsing the src and the download looks straight forward - i didn't find the resolver for the{media} binding in the routes/api.php
```
Route::get('/download/{media}', [DownloadMediaController::class, 'show']);
```

that is used to inject the Media in the show Method in DownloadMediaController.php. 
```
class DownloadMediaController extends Controller
{
    public function show(Media $media)
    {
        return $media;
    }
}
```

So my guess is that the Laravel internal **implicit** route model binding is used and resolves the wrong Media Model?

I hope i could shave off a few minutes of debugging and work :)
Thanks for a great package! :+1:

**Comment by newtongamajr** [comment]
@nlappe That's a nice shot. My suspect is that something may be using the original Media model instead of the one assigned into media-library config file!
