### ISSUE TITLE
Nova 3 / Laravel 7 support?

### ISSUE THREAD

**Issue by Sky7ure** [ebess/advanced-nova-media-library#156]
Does the author plan to add Laravel 7 and Nova 3 support soon?^_^

**Comment by rickgoemans** [comment]
I guess we'll have to wait for the author to accept this pull request:
https://github.com/ebess/advanced-nova-media-library/pull/155

**Comment by ijpatricio** [comment]
@Sky7ure check here https://github.com/ebess/advanced-nova-media-library/pull/155#issuecomment-597318499

**Comment by Sky7ure** [comment]
Thanks, I know how to pull them. When the package author themselves does it though, updating composer will still be faster, I noticed.

**Comment by VeeeneX** [comment]
It looks like https://github.com/ebess/advanced-nova-media-library/pull/158 has to be merged first

**Comment by jnbn** [comment]
I'm switching to shirshak55/advanced-nova-media-library for now. 

Hey @ebess do you need any help on maintenance?

If so, I think there may be some volunteers in here. Otherwise we're willing to take over as Epigra.

**Comment by VeeeneX** [comment]
We might also join as qolab, if you need some help :)

**Comment by jnbn** [comment]
Thank you @VeeeneX 👍

**Comment by ebess** [comment]
@jnbn Hi, unfortunately there is no way I can maintain this package/repo anymore. I'd love to add a another owner to this repo otherwise I will have abandon this package. I there someone willing to help?

**Comment by ebess** [comment]
ps: i will take a look into the PR an merge it if it works out despite looking for somebody to maintain for now until there is more room / time for me to take care of this

**Comment by Sky7ure** [comment]
I would suggest adding @ebess as another owner for the newly created and maintained package by [bkintanar](https://github.com/bkintanar/advanced-nova-media-library).

**Comment by ebess** [comment]
merged the PR for new versions and create a 3.0.0 release! will close this issue for now.

**Comment by VeeeneX** [comment]
@ebess Sorry to hear that, @bkintanar made recent changes and we as @qolab may participate as well. I would love to help

**Comment by jnbn** [comment]
We can support as much as we can (as Epigra) too @VeeeneX .

I think it'd be better to continue as contributors to this package instead of abandoning it and create a new composer dependency.

@bkintanar what do you think about it?

**Comment by VeeeneX** [comment]
I agree, that would be awesome!

**Comment by ebess** [comment]
I invited you three to be collaborators, I will also try to help/develop this package further whenever I can. Thanks in advance!

**Comment by bkintanar** [comment]
thanks for the invite! already accepted it.
