### ISSUE TITLE
Vapor Support

### ISSUE THREAD

**Issue by jayjfletcher** [ebess/advanced-nova-media-library#164]
Has anyone been able to add Vapor support?

**Comment by shirshak55** [comment]
hmm if media library supports then this package should support it right? So it depends if media library support or not.

**Comment by ebess** [comment]
vapor deploys laravel projects right? what's the problem regarding this package and vapor?

**Comment by Christophvh** [comment]
Nova 3 has added 2 extra field types for this usecase
https://nova.laravel.com/docs/3.0/resources/fields.html#vapor-file-field

**Comment by bkintanar** [comment]
@Christophvh sadly I don't have a vapor account to test something like this.

**Comment by ebess** [comment]
dont get the problem. you need to upload to s3 and everything should work right?

**Comment by Christophvh** [comment]
> dont get the problem. you need to upload to s3 and everything should work right?

Yes that will work, but requires some custom code. As noted in the nova documentation:

> When uploading a file using a VaporFile field, Nova will first generate a signed storage URL on Amazon S3. Nova will then upload the file directly to temporary storage in the Amazon S3 bucket. When the resource is saved, Nova will move the folder to permanent storage.

**Comment by ebess** [comment]
Ok I see as vapor has no persistent local storage. but this package does not use any temporary storage. it depends how you configure your media library. there is no way to make it work with a local storage using vapor, isn't it? media library will not work using vapor if you are not using any cloud storage.

**Comment by Christophvh** [comment]
Yes you are correct. The current project doesn't have any blockers to make it work. I think the main thing people struggle with is Signed-URLs. Working with temporary signed URLs in nova is a real pain. I only can get it working when setting my filesystem driver to public visibility. Private files always have broken previews with this package.

My current solution is to set the files to public for use in Nova and output a temporary URL to our SPA front-ends with a temporary more secure file link. But this still is a security issue when a user can get hold of the nova urls.

**Comment by ebess** [comment]
Ok, but if you want some real privacy e.g. only logged in users can see their own files, you need to proxy the files through your own controller. What I used to do is to create my [custom url generator](https://docs.spatie.be/laravel-medialibrary/v8/advanced-usage/generating-custom-urls/) for the library and pass through the file if the user if authorized to see it.

Temporary/signed urls do not add traffic to your server, but there are also some downsides whatsoever. That might be a bit offtopic, tho. So there is a need to add temporary url support, as I understand it. But you could also make it work using vapor as there is nothing special (I deploy via kubernetes, some "problem"). For now I will close this issue as there is no problem regarding vapor. If there is, let me know :)

**Comment by martin-ro** [comment]
> Ok, but if you want some real privacy e.g. only logged in users can see their own files, you need to proxy the files through your own controller. What I used to do is to create my [custom url generator](https://docs.spatie.be/laravel-medialibrary/v8/advanced-usage/generating-custom-urls/) for the library and pass through the file if the user if authorized to see it.
> 
> Temporary/signed urls do not add traffic to your server, but there are also some downsides whatsoever. That might be a bit offtopic, tho. So there is a need to add temporary url support, as I understand it. But you could also make it work using vapor as there is nothing special (I deploy via kubernetes, same "problem"). For now I will close this issue as there is no problem regarding vapor. If there is, let me know :)

Im using a custom url generator too, but the download of files works always. Download path is something like `/nova-vendor/ebess/advanced-nova-media-library/download/4` which always grants access. Where is the download url actually generated?

**Comment by shaffe-fr** [comment]
@Christophvh Did you achieved using the nova media library Images field with SignedURLs for vapor?

**Comment by thomaskenne** [comment]
@shaffe-fr @Christophvh @jayjfletcher Hi. Did any of you manage to get this working? I would hate to let vapor go over this...

**Comment by shaffe-fr** [comment]
@thomaskenne I ended up not using the package and writing custom Media and Image fields to handle Spatie media library media.

**Comment by thomaskenne** [comment]
@shaffe-fr ok. With cropping, sorting and everything?

**Comment by shaffe-fr** [comment]
@thomaskenne hopefully for me, only single files where required.
For the cropping, sorting, optizing part, I'll using a small EC2 instance with a server to server API to only manage image processing.
