### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by OpenHaus** [ebess/advanced-nova-media-library#18]
Is it possible to generate [responsive images](https://docs.spatie.be/laravel-medialibrary/v7/responsive-images/getting-started-with-responsive-images) through the library? 

If so how? If not that would be a great feature!

**Comment by ebess** [comment]
It's up to you to define the responsive images: https://github.com/ebess/advanced-nova-media-library#model-media-configuration. Do you want to display responsive images inside nova?

**Comment by OpenHaus** [comment]
I was referring to the automatic way provided by the library rather than configuring that myself. See url above. I didn´t find a way or the place to add the needed method call: `->withResponsiveImages()`

```
$yourModel
   ->addMedia($yourImageFile)
   ->withResponsiveImages()
   ->toMediaCollection();
```
It could be I am missing something obivious...

**Comment by ebess** [comment]
So if you define it inside the model, the medialib will generate responsive images on uploading new images ([see docs](https://docs.spatie.be/laravel-medialibrary/v7/responsive-images/getting-started-with-responsive-images#generating-responsive-images-for-conversions)). Does it work out for you?
