### ISSUE TITLE
Add support custom files

### ISSUE THREAD

**Issue by bigperson** [ebess/advanced-nova-media-library#19]
I would like to use the library to attach any files - not images.

**Comment by ragingdave** [comment]
Depending on the jameslkingsley package for File uploads seems to be broken or at least no longer maintained, I submitted a PR, and have heard nothing for now over a month. Perhaps not relying on that package at all would be the best course here.

**Comment by ebess** [comment]
2.0.0 release: https://github.com/ebess/advanced-nova-media-library#generic-file-management
