### ISSUE TITLE
App\Modules\Images\Models\Media not Found

### ISSUE THREAD

**Issue by joachimVT** [ebess/advanced-nova-media-library#2]
Why are you using  `use App\Modules\Images\Models\Media;`

Shouldn't this be `use Spatie\MediaLibrary\Models\Media;` ?

```
<?php

namespace Ebess\AdvancedNovaMediaLibrary\Fields;

use App\Modules\Images\Models\Media;
use Illuminate\Support\Collection;
use Laravel\Nova\Fields\Field;
use Laravel\Nova\Http\Requests\NovaRequest;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Illuminate\Support\Facades\Validator;
```

**Comment by ebess** [comment]
ty, I extracted this package from my companies code base and forgot to adjust. bugfix has been released.
https://github.com/ebess/advanced-nova-media-library/releases/tag/0.1.3
