### ISSUE TITLE
Set name and filename from nova interface

### ISSUE THREAD

**Issue by bigperson** [ebess/advanced-nova-media-library#20]
I would like to be able to specify the file name from the nova interface:
https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files#usingname
https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files#usingfilename

**Comment by ebess** [comment]
`usingfilename` see docs
https://github.com/ebess/advanced-nova-media-library#names-of-uploaded-images

feel free to create a PR for `usingname` should be straight forward

**Comment by ebess** [comment]
see https://github.com/ebess/advanced-nova-media-library#names-of-uploaded-images
