### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by affektde** [ebess/advanced-nova-media-library#205]
Laravel 8 was released. It would be great if this package is also tagged for the new version.

**Comment by bkintanar** [comment]
@affektde will try to tag a release today or tomorrow. hafta work. :D

**Comment by rickgoemans** [comment]
The support is added in composer.json but you forgot to tag a release. Could you make one?

**Comment by bkintanar** [comment]
@rickgoemans yeah, I'm aware. I'm still waiting for a PR to be merged.

**Comment by horaceho** [comment]
As a temporary patch to the `composer.json` for a newly upgraded Laravel 8 project ...
```
"require": {
    "ebess/advanced-nova-media-library": "dev-master#47256b275a66ba7e009dddf62e1adf2ffac70881 as 3.3"
},
```

**Comment by rickgoemans** [comment]
Still waiting for a new tag...

**Comment by lyc2468** [comment]
Still waiting.

**Comment by stepanenko3** [comment]
**@bkintanar**, still waiting for a new tag

**Comment by bkintanar** [comment]
Sorry guys. Will create a tag now.

**Comment by bkintanar** [comment]
tagged 3.3.0
