### ISSUE TITLE
Cant use Field Help Text in Files

### ISSUE THREAD

**Issue by bcoelhodev** [ebess/advanced-nova-media-library#208]
Hi,

<img width="484" alt="Captura de ecrã 2020-10-16, às 14 30 19" src="https://user-images.githubusercontent.com/13311052/96264567-415fd580-0fbc-11eb-9265-040d68f7c66b.png">

In Images works fine, like this
```
Images::make('Images', 'gallery')
->singleMediaRules(['mimetypes:image/jpg,image/jpeg,image/png'])
->help('.jpg, .jpeg or .png'),
```
In Files doesn't work
```
Files::make('File', 'file')
->rules('required')
->singleMediaRules(['mimes:pdf,zip,jpef,jpg,png'])
->help('Pdf, Zip, Jpeg, Jpg, Png'),
```

**Comment by bcoelhonqda** [comment]
I create PR https://github.com/ebess/advanced-nova-media-library/pull/217 to resolve this.

**Comment by bcoelhonqda** [comment]
I create PR #218 to fix this.

**Comment by yarbala** [comment]
For me not works for Images also :(
