### ISSUE TITLE
Media library using guid

### ISSUE THREAD

**Issue by muswanto** [ebess/advanced-nova-media-library#23]
I found a bug when using guid on my media table.
![image](https://user-images.githubusercontent.com/816709/48357249-b5a3e700-e6ca-11e8-9cd6-857b367fe8bf.png)

That is on file vendor\ebess\advanced-nova-media-library\src\Fields\Images.php
I'm using guid in media table and cast to integer will make an exception.. 
For now I just remove "(int)" and everything working well..

**Comment by ebess** [comment]
feel free to create a pr
