### ISSUE TITLE
I need to store images into perticular folder

### ISSUE THREAD

**Issue by yatin13490** [ebess/advanced-nova-media-library#25]
Hi,

I had used the [spatie lib docs.](https://docs.spatie.be/laravel-medialibrary/v7/installation-setup), without this nova package, In that project, my requirement is to store the user's images into the user folder, blog images in the blog folder,

so, Lravel media library gives an option: 
toMediaCollection(collection name', 'disk_name');
I achieved my requirement through this,
Now, with Nova, I like to do the same, like store the user related images under user folder, and other images are under the related folder,
I can change the collection name through this:
Images::make('Photo', 'user') // second parameter is the media collection name 

but how can I change the disk_name. (currently, all the images are stored under public directory directly)

**Comment by aramirez92** [comment]
Have you solved the problem?

**Comment by aramirez92** [comment]
File: `filesystems.php`

I've added a new disk

````
'media' => [
            'driver'    => 'local',
            'root'      => public_path('media'), 
            'url'       => env('APP_URL') . '/media',
        ],
````

**Comment by ebess** [comment]
```php
Images::make('Main image', 'main')->enableDisks() // all disks available
// or
->enableDisks(['disk1', 'disk2'] // all given available
```
I guess this feature would work fine with https://github.com/ebess/advanced-nova-media-library/pull/35

**Comment by yatin13490** [comment]
@ebess 

It gives me error like enableDisks does not exist
![screenshot-seasons sr-2018 12 10-17-54-52](https://user-images.githubusercontent.com/6308981/49732473-dac54e80-fca4-11e8-9bec-e7769ad57780.png)

**Comment by ebess** [comment]
@yatin13490 I was talking about somebody implementing `enableDisks`. It's not there yet, so feel free to create a PR.
