### ISSUE TITLE
Not able to preview in detail and index page

### ISSUE THREAD

**Issue by swapnilnandgave** [ebess/advanced-nova-media-library#252]
When I upload image in create page then it is getting saved in both media table and public path. It is very strange how is it happening. I can't see those images in detail screen.
![Screenshot 2021-04-06 at 3 27 01 PM](https://user-images.githubusercontent.com/1922846/113693802-a0411480-96ec-11eb-86aa-67aa35c359b2.png)
![Screenshot 2021-04-06 at 3 27 19 PM](https://user-images.githubusercontent.com/1922846/113693819-a33c0500-96ec-11eb-91cc-47b519ea2d59.png)
![Screenshot 2021-04-06 at 3 28 59 PM](https://user-images.githubusercontent.com/1922846/113693959-d1b9e000-96ec-11eb-8417-fa4f394d7c8a.png)
![Screenshot 2021-04-06 at 3 28 29 PM](https://user-images.githubusercontent.com/1922846/113693997-db434800-96ec-11eb-935e-fbf0178f76be.png)

I have attached screenshots for more information. Somebody help what am I doing wrong here?

**Comment by kieranmcclure** [comment]
Were you able to solve this? @swapnilnandgave

**Comment by swapnilnandgave** [comment]
Yes. I have resolved that. You have to provide exact name that you mentioned in second arguments while fetching
