### ISSUE TITLE
Could you release new functionality

### ISSUE THREAD

**Issue by BobbyBorisov** [ebess/advanced-nova-media-library#262]
@ebess hey! first of all thanks for the awesome package!

I saw you now support temporary urls thanks for @carlcassar since 15 April but there is no new release. It would be awesome to release the package in order to receive the new functionality. 

Thanks in advance! 

Cheers,
Bobby

**Comment by bkintanar** [comment]
@BobbyBorisov sorry for the delay. Been here and there lately. I'll setup a new release.

**Comment by BobbyBorisov** [comment]
Thanks @bkintanar! I owe you a beer! 🍺

**Comment by bkintanar** [comment]
No worries. Thanks for the reminder, I forgot that I need to release a version for this package. 🤦
