### ISSUE TITLE
SVG refused

### ISSUE THREAD

**Issue by tanthammar** [ebess/advanced-nova-media-library#27]
I defined one of my Mediacollections to allow svg:s.
When I try to upload an svg I get the error; "must be an image".

```
$this->addMediaCollection('logo')
            ->singleFile()
            ->acceptsFile(function (File $file) {
                return in_array($file->mimeType, ['image/jpeg', 'image/png', 'image/gif', 'image/tiff', 'image/webp', 'image/svg+xml']);
            });
```

**Comment by audetcameron** [comment]
Any update on SVG support in laravel nova?

**Comment by sigaev-pro** [comment]
SVG is a must-have feature for nowadays!

**Comment by idragon81** [comment]
I can confirm SVG works partially.
This library is using Laravel's image validation. Laravel seems to have an issue while validating SVGs with mime type **image/svg**, but it works fine for mime type **image/svg+xml**

I have raised an issue with laravel https://github.com/laravel/framework/issues/26990

For the meantime I can only suggest you to change the mime type. Most SVG Cleaners and optimizers do this for you.

**Comment by ArmeniaH** [comment]
any other solutions for this, svg really is a must. Maybe we can override the core to have our own validation ?

**Comment by ebess** [comment]
Checked it with laravel 5.8, working fine.

**Comment by nemrutco** [comment]
i am on laravel 5.8 faced the issue today. Can't upload svg usuing Image field. i get the error ".. must be an image." Can you confirm it's working?

**Comment by nemrutco** [comment]
Just figure out, Correct it works fine. But you have to make sure your svg contains <?xml version="1.0" encoding="iso-8859-1"?> in first line, Some svg files does not has <?xml version="1.0" encoding="iso-8859-1"?> (for example font-awesome svg files). So this cause validation error.
