### ISSUE TITLE
Please add support for "Custom Properties"

### ISSUE THREAD

**Issue by tanthammar** [ebess/advanced-nova-media-library#28]
I would be very happy if it was possible to add support for Spatie Media Library customProperties method.

To use, something like this:
```
Images::make('Logo', 'logo')
            ->withCustomProperties([
                'team_id' => $request->user()->current_team_id,
                'user_id' => $request->user()->id,
                'title' => 'Company Logo'
            ]),
```

**Comment by msassa** [comment]
#33 I already make the pull request

**Comment by ebess** [comment]
see release 2.0.0 https://github.com/ebess/advanced-nova-media-library#custom-properties
is there any need of kind of merging some code-based attributes on top on the custom properties in the form?

**Comment by ragingdave** [comment]
@ebess Yes on the code-based attributes if possible. It allowed for predefined, non-user editable metadata about an image in a collection which at least in my case was vital. I can probably find a way around this but it would be much easier to have the ability to define the properties.
