### ISSUE TITLE
Media ID in folders

### ISSUE THREAD

**Issue by jfvoliveira** [ebess/advanced-nova-media-library#29]
Hi there. I'm trying to use this package to upload multiple images to a Resource in Nova.

The thing is, I'm creating the resource with the ID of 24 and I'm uploading 3 images. The result is 3 folders, named 1, 2 and 3 that are created each for an uploaded image. Inside I have the image and the conversions.

Wasn't it supposed to be all stored in a folder called 24 and then inside I would have the 3 images and the conversions folder?

What am I doing wrong?

Thanks!

**Comment by FaridAghili** [comment]
Hi,
This package is using Spatie's Media Library package. What you explained is caused by the underlying package:
https://github.com/spatie/laravel-medialibrary
