### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by deckchan** [ebess/advanced-nova-media-library#297]
As I know, spatie/laravel-medialibrary already support L9.

Any news for ebess/advanced-nova-media-library supporting L9?

Thanks!!

**Comment by bkintanar** [comment]
Will try to look into this sometime this weekend.

**Comment by deckchan** [comment]
Thanks so much!!!!

**Comment by BrekiTomasson** [comment]
Connected to Laravel 9 support should also be support for `spatie/laravel-medialibrary` v10.

**Comment by kevariable** [comment]
Great !

**Comment by degecko** [comment]
Any news on this, please?

**Comment by manuglopez** [comment]
I have ended making  this in my composer.json after editing this package composer.json file to be compatible with laravel 9

```
{
            "type": "path",
            "url": "./nova-components/advanced-nova-media-library-master"
 }
```
Waiting anyway for the upgrade.

**Comment by bkintanar** [comment]
Sorry guys didn't had time to work on it during the weekend. I'll try to review it this week.

--
Bertrand Kintanar
***@***.***

**Comment by bkintanar** [comment]
Laravel 9 support released.
