### ISSUE TITLE
Can't add same image after removing it

### ISSUE THREAD

**Issue by lucasromanojf** [ebess/advanced-nova-media-library#31]
Steps to reproduce:

1) Create a single file upload field for the resource;
2) Go to the resource's create page;
2) Select an image (let's call it "A");
3) Remove the "A" image without uploading it;
4) Select the same "A" image again;
5) Nothing happens :disappointed:;
6) Select another image "B";
7) It works! :smiley:
8) Select the "A" image again and it now works too.

BTW, thanks for the package, very great job so far!

**Comment by ebess** [comment]
@lucasromanojf Hi, tried to reproduce, but couldn't. Work's fine for me! Failing on the most recent version for you?
