### ISSUE TITLE
Support Nova 4

### ISSUE THREAD

**Issue by cwray-tech** [ebess/advanced-nova-media-library#313]
Now that Nova 4 is out, it would be great if we could update this package to support it. Let me know if you need any help with this and I may be able to dedicate some time to it.

**Comment by Kussie** [comment]
Should already support Nova 4.0 as of 3.8.0 released a few hours ago.

https://github.com/ebess/advanced-nova-media-library/pull/309

**Comment by cwray-tech** [comment]
@Kussie thank you!
