### ISSUE TITLE
[4.x] Bug when viewing the file within details page

### ISSUE THREAD

**Issue by bkintanar** [ebess/advanced-nova-media-library#319]
The PR looks good after I tested it on my local. However, for viewing the file within the details page it says `[object Object]`. I'm using `Files::make('Single File')` in my case. :) 

<img width="527" alt="image" src="https://user-images.githubusercontent.com/10015302/164278349-1097095d-d97b-4356-bd3e-62820e477539.png">

_Originally posted by @harlekoy in https://github.com/ebess/advanced-nova-media-library/pull/317#issuecomment-1104138169_

**Comment by mucenica-bogdan** [comment]
Found the issue, working on a patch now. PR should ready ready in about 1-2h. I want to fix a couple of other issues reported here: https://github.com/ebess/advanced-nova-media-library/issues/320
