### ISSUE TITLE
Ratio for cropping does not work in Nova 4.0

### ISSUE THREAD

**Issue by Hannoma** [ebess/advanced-nova-media-library#322]
```php
->croppingConfigs([
    'ratio' => 1
])
```
This does not work anymore

**Comment by mucenica-bogdan** [comment]
Added a fix for this in this PR: https://github.com/ebess/advanced-nova-media-library/pull/324

Hopefully it will get merged soon.

**Comment by bkintanar** [comment]
https://github.com/ebess/advanced-nova-media-library/releases/tag/4.0.2 marking this as fixed.
