### ISSUE TITLE
Compatibility issue with Laravel 10

### ISSUE THREAD

**Issue by fh32000** [ebess/advanced-nova-media-library#379]
I'm trying to use this package in my Laravel 10 project, but I'm encountering an error related to compatibility. I believe there is a conflict between the requirements of package and Laravel 10. Can you please help me resolve this issue?

```
{
    "require": {
        "php": "^8.1",
        "laravel/framework": "^10.0",
        "ebess/advanced-nova-media-library": "^4.0.5"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires ebess/advanced-nova-media-library ^4.0.5 -> satisfiable by ebess/advanced-nova-media-library[4.0.5, 4.x-dev].
    - ebess/advanced-nova-media-library[4.0.5, ..., 4.x-dev] require laravel/framework ^8.0|^9.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).

```

**Comment by NadsonKT** [comment]
Same problem here, waiting for solution...

**Comment by fh32000** [comment]
@NadsonKT 
see #374

**Comment by fh32000** [comment]
@happyDemon @jnbn @Nks 
any updates

**Comment by happyDemon** [comment]
Why would I have updates? Contact the owner of the repo

**Comment by jxclsv** [comment]
Still not working?

**Comment by merijnponzo** [comment]
Please make it laravel 10 compatible

**Comment by Sergej-Tihonov** [comment]
@bkintanar the upgrade is working well from merged pull request: https://github.com/ebess/advanced-nova-media-library/pull/374
Please create a new release of this package, so we have Laravel 10 support.
I have tested it in my projects with the dev version. No adjustments where necessary. Working as before.
