### ISSUE TITLE
Anoter disk_name in the config `nova-media-library.php`

### ISSUE THREAD

**Issue by sunnydesign** [ebess/advanced-nova-media-library#390]
Hi guys!

I have a problem with config.
I need to separate production storage on S3 from local storage on local disc via `.env`.

For example, I have 2 discs in my config `filesystems.php`:

```
'media_local' => [
    'driver' => 'local',
    'root' => storage_path('app/public/media'),
    'url' => env('APP_URL').'/storage/media',
    'visibility' => 'public',
],

'media_s3' => [
    'driver' => 's3',
    'key' => env('DO_ACCESS_KEY_ID'),
    'secret' => env('DO_SECRET_ACCESS_KEY'),
    'region' => env('DO_DEFAULT_REGION'),
    'bucket' => env('DO_BUCKET'),
    'url' => env('DO_URL'),
    'endpoint' => env('DO_ENDPOINT'),
    'use_path_style_endpoint' => env('DO_USE_PATH_STYLE_ENDPOINT', false),
    'visibility' => 'public',
],
```
Also I have in the config `media-library.php`:

```
'disk_name' => env('MEDIA_DISK', 'media_local'),
```

In my production `.env` I want to use:
```
MEDIA_DISK=media_s3
```

But in my local `.env` I want to use:
```
MEDIA_DISK=media_local
```

After that I try to add in the config `nova-media-library.php`:

```
'disk_name' => env('MEDIA_DISK', 'media_local'),
```

But it doesn't work.

So, as a result, I can to configure disk in  the `media-library.php` but cannot to configure one in the `nova-media-library.php`.

How can I solve this problem?

**Comment by Elshaden** [comment]
+1

**Comment by sunnydesign** [comment]
I'll answer myself.

When we upload the image, the Media Library save `disc` related by this image to db column `disc`. In this case we cannot choose the `disc` depending environment, because it's already defined.

But we can define one `disc` in the config with condition like this:

```
'media' => App::environment() === 'production'
? [
    'driver' => 's3',
    'key' => env('DO_ACCESS_KEY_ID'),
    'secret' => env('DO_SECRET_ACCESS_KEY'),
    'region' => env('DO_DEFAULT_REGION'),
    'bucket' => env('DO_BUCKET'),
    'url' => env('DO_URL'),
    'endpoint' => env('DO_ENDPOINT'),
    'use_path_style_endpoint' => env('DO_USE_PATH_STYLE_ENDPOINT', false),
    'visibility' => 'public',
] : [
    'driver' => 'local',
    'root' => storage_path('app/public/media'),
    'url' => env('APP_URL').'/storage/media',
    'visibility' => 'public',
],
```

**Comment by damarinov1** [comment]
I have stumbled upon your question as I am doing the same thing at the moment. And OMG, this is ridiculous if that is the workaround that we'll have to do.

**Comment by rushabh-indianic** [comment]
I think I have similar problem
I have migrated my development environment from `public` to `s3` disk
I have set default disk to `s3` in `config/filesystems.php`
But it is still storing in public folder
