### ISSUE TITLE
Add Cropping Support to Images

### ISSUE THREAD

**Issue by idragon81** [ebess/advanced-nova-media-library#44]
Using media conversion does help in restricting the max resolution. However it would be great if we could enforce the aspect ratio

**Comment by ebess** [comment]
you can do so by adding proper validation:
https://laravel.com/docs/5.7/validation#rule-dimensions

**Comment by idragon81** [comment]
I meant to have a client side cropper like https://github.com/64robots/nova-image-cropper

**Comment by ebess** [comment]
@idragon81 just released support for cropping with 2.5.0
