### ISSUE TITLE
Translate strings

### ISSUE THREAD

**Issue by diegorodriguezvidal** [ebess/advanced-nova-media-library#49]
First of all, nice package! :)

Is it possible to translate the plugin? Strings such as "Add New Media", "Replace Media", "Add New File"...

**Comment by ebess** [comment]
if you publish novas vendor assets, you can just add the translation string to:
`resources/lang/vendor/nova/en.json` (or some other language)

```
{
    // ...
    'Add New Media': 'Your Translation',
    // ...
}
```

**Comment by Anticom** [comment]
I found it interesting, that it's not honnoring `resources/lang/<lang>.json` but it *has to be* nova's translations. Could anyone explain this to me?

**Comment by SquareBeard** [comment]
This does not work for strings like "Remove" and "Download".
Is there another way ?

**Comment by mathiasmadsen** [comment]
> I found it interesting, that it's not reading from `resources/lang/<lang>.json` but it _has to be_ nova's translations. Could anyone explain this to me?

I am curious about this setup as well. Could this at least be documented? I usually have custom strings in `resources/lang/<lang>.json,` so the Nova translations can stay in sync with the original json string :)
