### ISSUE TITLE
Custom Properties not saving vaules

### ISSUE THREAD

**Issue by cyclops1101** [ebess/advanced-nova-media-library#50]
I've tried using the custom property field as the documentation presents but it won't save any values. If the property doesn't already exist it will create the key but it will only ever set it to `null`

`Images::make('Image')
                ->customPropertiesFields([
                    Boolean::make('Active'),
                    Markdown::make('Description'),
                ])`

In addition the custom property popup doesn't block the keyup detection on the detail page, meaning if I open the popup on the detail page and try to type into a field it navigate to the edit view when an `e` is pressed.  Not sure if you'd want to remove the popup on the detail page altogether or override that keyup event.

**Comment by litalboa** [comment]
@ebess there is a solution to this?

**Comment by ebess** [comment]
@cyclops1101 @litalboa 

The detailview is not the proper place to edit some data on the product / products media imo. All custom properties are not saved by clicking the `update` button on the modal. You need to `update/create` the whole model.

Beside that, do custom properties work as expected on the edit view?

Will remove the edit custom properties icon from detail view.

**Comment by cyclops1101** [comment]
I still can't get the custom property fields to hydrate nor save when I use the form fields.

**Comment by cyclops1101** [comment]
Looking at the HandlesCustomPropertiesTrait the fillMediaCustomPropertiesFromRequest method doesn't interact with the media object.  Adding the code below into the foreach loop got the media model to update appropriately.  

`$value = $request->{$collection . "-custom-properties"}[$index][$field->attribute];`
`$media->setCustomProperty($field->attribute,`
`$field->component === 'boolean-field' ? !!$value : $value);`

**Comment by glebihan** [comment]
In case someone else faces this issue, I've noticed that the current code is only compatible with Laravel >= 5.7.
Setting custom properties on Laravel 5.6 won't work. This is the commit involved : https://github.com/laravel/framework/commit/1fa9459a82fadc5958b0ae1b6b549ed32c0867f8
