### ISSUE TITLE
Put Uploads Into Queue

### ISSUE THREAD

**Issue by nickpoulos** [ebess/advanced-nova-media-library#54]
First off, excellent package, I have been using since the early versions and it has just continued to get even better. Thank you.  

An "issue" I am having is the lag when uploading several files at once, especially for an image gallery or video file. The issue becomes compounded when using any image conversions, although Spatie's package allows passing those to a queue behind the scenes. But it would be great to be able to push the main uploads to a background job/queue. 

Thoughts?

**Comment by ebess** [comment]
The laravel media lib does queue the conversion by default, doesn't it?

see https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions#queuing-conversions

I don't think it does make sense to queue the pushing to media lib disk. Potentially your queue workers are running on different machines.
