### ISSUE TITLE
Can i use Adding custom properties ?

### ISSUE THREAD

**Issue by slion0725** [ebess/advanced-nova-media-library#6]
Adding custom properties
[Link](https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-custom-properties
)
withCustomProperties method

**Comment by ebess** [comment]
Hi, for now you can't. how you supposed to enter those properties when adding a new image? Via modal maybe?

**Comment by slion0725** [comment]
Hi, I try the model : registerMediaCollections() , this is MediaCollection
Can't use setCustomProperty() .... is sad!!

**Comment by ebess** [comment]
https://github.com/ebess/advanced-nova-media-library/pull/35
