### ISSUE TITLE
Cannot upload Image 

### ISSUE THREAD

**Issue by petyots** [ebess/advanced-nova-media-library#73]
Hello again :) 
I just tried to upload a single image following your guide and there seems to be a error 
![image](https://user-images.githubusercontent.com/14016592/56602061-4af5c080-6605-11e9-90d5-a4fc3af86a2c.png)
I think it's because of wrongly typed property in some of the components but i am still tryin to find it... Thanks in advance

**Comment by ebess** [comment]
Hi,
would you mind sharing your field / model configuration & image you are trying to upload?

**Comment by petyots** [comment]
Hi this is the photo i am trying to upload:
![Screenshot 2019-04-01 at 16 40 37](https://user-images.githubusercontent.com/14016592/56686690-371d8d80-66dd-11e9-8c8c-4bf41b346d93.png)

this the field config in the resource:
`return [
ID::make()->sortable(),
            new Panel('General', [
                Images::make('Logo', 'logo')->conversion('logo'),
                Translatable::make([
                    Text::make('Name'),
                    Text::make('Slug')->hideFromIndex(),
                    Textarea::make('Short Description')->hideFromIndex()
                ]),
                BelongsTo::make('Status', 'status'),
                Boolean::make('Display', 'display'),
                Textarea::make('Notes'),
            ]),
]`

This is the model (only the conversions and the collections )

`public function registerMediaCollections()
    {
        $this->addMediaCollection('logo')->singleFile();
        $this->addMediaCollection('cover')->singleFile();
        $this->addMediaCollection('gallery');
    }

    public function status()
    {
        return $this->belongsTo(Status::class);
    }`

**Comment by ebess** [comment]
working fine for me. have you tried to remove all other fields but the images?
which browser are you using?

**Comment by tigerstrikemedia** [comment]
Hi Guys, I ran into this issue this afternoon, and as I need this for a project with a deadline, and not one who can sleep with weird bugs I went ahead and sorted it out. 

Was in Scissors.vue.

In the process of sorting that out there was a breaking change in loading components so I added `.default` to the end of the imports as well.

Have submitted a pull request. 

https://github.com/ebess/advanced-nova-media-library/pull/77

Thanks
Ben

**Comment by xenonthong** [comment]
Having the same exact issue here too.

**Comment by ebess** [comment]
@tigerstrikemedia ty, 2.5.3 released

**Comment by xenonthong** [comment]
@ebess Packagist 2.5.3 still doesn't contain this fix though.

**Comment by tigerstrikemedia** [comment]
@ebess Confirming that the 2.5.3 release does not contain my fix.
