### ISSUE TITLE
[Advice needed] For displaying 'pending' or placeholder image whilst conversions complete

### ISSUE THREAD

**Issue by dannylepage** [ebess/advanced-nova-media-library#76]
Hi and thanks for the great library!

I'm using the library to perform conversions in the background using a queue. When clicking 'Update resource' after adding a given image, I'm usually finding that the resource details page has loaded before the image upload and conversion has completed and thus a a broken image link is shown in the image preview (as shown below).

![Screenshot 2019-04-25 at 17 13 10](https://user-images.githubusercontent.com/1552482/56751372-d09c7c00-677d-11e9-9bbc-5cfe5fba7569.png)

I'm wondering if there's a nice way of informing the user that the image isn't 'ready' yet, by the use of a placeholder or something to indicate work is still being performed on the image?

Cheers!

**Comment by ebess** [comment]
@dannylepage Hey mate, good point. 

1. Probably need to check when passing the image urls to the frontend whether the converion has been generated. If not, just show the original image. Which implicates you will see not the real thumbnail conversion and the image might change on next reload. Which is fine if you just scale down the original one.
2. Another option would be to show some kind of loading indication and poll for thumbnail. The first option is easier tho.

**Comment by dannylepage** [comment]
Thanks a lot for the quick reply @ebess 👍

Option 1 sounds like the way to go, thanks! 
When using conversions, is it possible to not specify a conversion for the preview image on the model view (i.e. use the original image instead)? I've noticed the `conversionOnView({conversion})` method, however, when I leave this off, it seems the last conversion performed gets used as the default preview image on the model default page, but in my case, it's common for the conversion not to have finished by the time the view is loaded, which is why I'd like to use the original image (if possible).

`withResponsiveImages()` seems to use the original image as the preview image in this way, even if other, specified conversions are used as part of the collection along with the responsive conversions, so I'm just curious is to whether I'm missing a trick!

I'm using v2.5.2.

Cheers

**Comment by ebess** [comment]
Hi @dannylepage 
Both options described above are not implemented yet. Only some idees I had. 

https://github.com/ebess/advanced-nova-media-library/blob/master/src/Fields/Media.php#L213

Need to check here whether the conversion was been generated. If so, return conversion otherwise the default image.

**Comment by ebess** [comment]
Well, just took a look in it, there has to be some kind of a racing condition of the filesystem. The conversion is marked as generated inside of the custom properties dispite not being available yet.

Imo it's not a big deal to configure a `nonQueued` conversion for for nova only. I will create an interface for setting conversions for the form view only. I will close this issue for now.
