### ISSUE TITLE
Multiple image upload

### ISSUE THREAD

**Issue by akmalelias** [ebess/advanced-nova-media-library#78]
Hi,
I saw this line in the readme.

> If you enable the multiple upload ability, you can order the images via drag & drop.

I have tried to figure out how to enable the multiple upload ability but can't find it & didn't managed to use this library until now. Can someone help to guide me on how to enable the multilple upload ability. Thanks

**Comment by amina-zeb** [comment]
Hey @akmalelias 
I am facing the same issue. How were you able to resolve this issue?
