### ISSUE TITLE
Form alignment for multiple images upload field

### ISSUE THREAD

**Issue by akmalelias** [ebess/advanced-nova-media-library#79]
Hi,

Why when using the multiple images upload, the form is not align same as other fields?
![image](https://user-images.githubusercontent.com/20658464/56892149-4de32c00-6ab1-11e9-94d7-69e303533a18.png)

Is there any way if I want to adjust the Gallery field so that it aligned with other fields?
Thanks

**Comment by ebess** [comment]
Hi @akmalelias 
Are you using `fullSize()` on your gallery field? If so, remove it.
