### ISSUE TITLE
cropping aspect ratio

### ISSUE THREAD

**Issue by atmediauk** [ebess/advanced-nova-media-library#80]
Hello, is it possible to show a cropbox with a fixed ratio.

For example would it be possible to do ``` ->croppable(1/1) ``` to in this case enforce a one to one ratio for vue-js-clipper. Similar to how this package does it - https://github.com/ctessier/nova-advanced-image-field

**Comment by Chema-TM** [comment]
> Hello, is it possible to show a cropbox with a fixed ratio.
> 
> For example would it be possible to do `->croppable(1/1)` to in this case enforce a one to one ratio for vue-js-clipper. Similar to how this package does it - https://github.com/ctessier/nova-advanced-image-field

It will be amazing!!!

**Comment by ebess** [comment]
@atmediauk @Chema-TM Hi, should be not that hard. I'll take a look in it!

**Comment by ebess** [comment]
released in 2.6.0, see docs https://github.com/ebess/advanced-nova-media-library#image-cropping
