### ISSUE TITLE
Uploading files requires setting croppingConfigs

### ISSUE THREAD

**Issue by atmediauk** [ebess/advanced-nova-media-library#81]
When adding a file field:

```
        return [
            Files::make('My Files', 'my_files')
        ];
```

The following error is displayed:

![image](https://user-images.githubusercontent.com/4824454/57773200-5f624000-770f-11e9-81b9-5775788b1f63.png)

I think the files upload is incorrectly expecting a cropping config e.g ```->croppingConfigs(['ratio' => 16/9])``` to work?

**Comment by ebess** [comment]
hi @atmediauk I pushed fix to master. Would you mind trying out `dev-master`? If it works, I'll draft a new release
