### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by metalcamp** [ebess/advanced-nova-media-library#82]
Description: 
Image validation fails, validation message 'image is required' is returned even when said image already exists in this collection - example: when updating resource. Such error does not appear in package version 2.6.0.

Laravel version: 5.8.17
Nova version: 2.0.3-2.0.5
Package version: >2.6.0 (both 2.7.0 and 2.7.1)

Field definition on Nova Resource
` Images::make('Image', 'collection-name')
                ->singleImageRules([
                   'dimensions:min_width=1920,min_height=640,ratio=3/1',
                   'mimetypes:image/jpg,image/jpeg,image/png'])
                ->rules('required')`

**Comment by dinandmentink** [comment]
Can confirm, also getting this error after updating.

**Comment by nezaboravi** [comment]
Same here, getting collection is required.

**Comment by ebess** [comment]
Ty for reporting, released fix in 2.7.2!
