### ISSUE TITLE
Media base table or view not found

### ISSUE THREAD

**Issue by KnowledgeWanderer** [ebess/advanced-nova-media-library#86]
I get this when I try to upload a bot_avatar on user:

![user bot_Avatar](https://user-images.githubusercontent.com/40168248/58098073-73131800-7be1-11e9-8628-affc8a7a8019.PNG)

And this

![2](https://user-images.githubusercontent.com/40168248/58098120-86be7e80-7be1-11e9-9d5e-6f6f8a5f12ad.PNG)

When I try to upload a header_image on a Page.

Am I retarded or should I create a migration for Media and what tables should it have if so?

You can find details about my code here:
#85

**Comment by ebess** [comment]
Hi again! Follow install instruction of the [Laravel Medialibrary](https://docs.spatie.be/laravel-medialibrary/v7/introduction). You need to install this package first.

**Comment by KnowledgeWanderer** [comment]
I love you
