### ISSUE TITLE
Image not showing, but downloading works

### ISSUE THREAD

**Issue by KnowledgeWanderer** [ebess/advanced-nova-media-library#87]
I need some help with media editing/showing once I uploaded it. I managed to solved the problems on #85 and #86 because @ebess is a god, but I need this last thing done and I can't figure it out.
![pic1](https://user-images.githubusercontent.com/40168248/58168053-06a62080-7c96-11e9-8e9c-0e652c0623b8.PNG)

Thing is that if I click the download link, it works. And it's the good image downloaded.
![pic2](https://user-images.githubusercontent.com/40168248/58168055-06a62080-7c96-11e9-823c-55bc30b7c462.PNG)

my User model
```
class User extends Authenticatable implements HasMedia
{
    use Notifiable;
    use HasMediaTrait;
...
...
...
public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(130)
            ->height(130);
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('bot_avatar')->singleFile();
    }
}
```

my User Resource

```
Text::make('Bot Name', 'bot_name')
                ->rules('required', 'max:255'),

Images::make('Bot Avatar', 'bot_avatar')
                ->thumbnail('thumb')
                ->rules('required'),
```

Is thumb the problem? What am I doing wrong this time?

Oh, almost forgot, couldn't make json table work on MariaDB, so I used string in the media migration
```
$table->string('manipulations');
$table->string('custom_properties');
$table->string('responsive_images');
```

**Comment by KnowledgeWanderer** [comment]
`$user->getMedia()` this gives me [], so I guess even if I can download the img and even if it's saved in the db, not even the method work?

**Comment by ebess** [comment]
Hey @KnowledgeWanderer  :wink: 
there has been a issue already about this problem: https://github.com/ebess/advanced-nova-media-library/issues/76. See my last comment. I hope this will work out for you!

**Comment by OthmanAlseagh** [comment]
still have this error on version 3.4.

any solutions??

**Comment by OthmanAlseagh** [comment]
@ebess

**Comment by monaye** [comment]
@ebess could be just forgotten to run `storage:link`  https://laravel.com/docs/8.x/filesystem#the-public-disk ?
