### ISSUE TITLE
Preview images missing on edit page when cropping is enabled.

### ISSUE THREAD

**Issue by xenonthong** [ebess/advanced-nova-media-library#88]
When cropping is not disabled, the preview images on the resource edit form will not show up.

```php
Images::make('Images', 'carouselImages')
                  ->conversionOnDetailView('thumb')                  
                  ->conversionOnForm('thumb')
                  ->onlyOnForms(),
```
![image](https://user-images.githubusercontent.com/9009371/58189736-9f1bbf80-7ced-11e9-83e8-883f24c0df8b.png)

**Comment by ebess** [comment]
Hi @xenonthong 
Which version of nova / this package are you using? I can not reproduce.

**Comment by xenonthong** [comment]
@ebess i'm using Nova version 1.3.2 and 2.7.2 for this package

**Comment by ebess** [comment]
Hmm I tried it but still can not reproduce. As it seems the field configuration is not passed to the `Gallary` component, right here: https://github.com/ebess/advanced-nova-media-library/blob/master/resources/js/components/Gallery.vue#L69. It's probably some interference with other packages, I guess. 

Maybe upgrading to nova ^2.0 will help.
