### ISSUE TITLE
Can you please increase the z-index of the edit modal.

### ISSUE THREAD

**Issue by tanthammar** [ebess/advanced-nova-media-library#93]
I have the form on the same page as a Leaflet.js map with an image source.
The modal to edit/crop an uploaded image needs to have **z-index: 400** (minimum, the map is on 399), to be above the leaflet map instance.

I would very be very happy if you can accept this change request, to avoid a fork for such a small issue :)

Attaching an image to show the current z-index and if you place it on 400.

## Current z-index
<img width="1194" alt="Skärmavbild 2019-06-10 kl  01 04 42" src="https://user-images.githubusercontent.com/21239634/59165466-513fed80-8b1c-11e9-9f7b-e0d775ce26fb.png">

## z-index 400
<img width="1194" alt="Skärmavbild 2019-06-10 kl  01 09 17" src="https://user-images.githubusercontent.com/21239634/59165472-6b79cb80-8b1c-11e9-9a8a-905baed5d0fc.png">

**Comment by ebess** [comment]
Looks good to me!

**Comment by ebess** [comment]
*On Master*
