### ISSUE TITLE
Validate files with Laravel mime validation rule

### ISSUE THREAD

**Issue by phuclh** [ebess/advanced-nova-media-library#94]
Can I validate file types by using Laravel mime validation rule?

Something like this:

```
Files::make('Guideline', 'articles')
                        ->rules('mimes:png')
```

I tried but it always shows the error: `The articles must be a file of type: png.` even I uploaded a png file.

My current solution is validating it in the `registerMediaCollections` method

```
public function registerMediaCollections()
    {
        $this->addMediaCollection('articles')
            ->acceptsFile(function (File $file) {
                $acceptedTypes = [
                    'image/png'
                ];

                return in_array($file->mimeType, $acceptedTypes);
            });
    }
```

But it will throw an exception when a user uploads an unaccepted file type that isn't a friendly alert.

**Comment by tobz-nz** [comment]
I'm having this problem as well.

Laravel 5.8.23
Nova 2.0.6

**Comment by fenestron** [comment]
You can use `singleMediaRules`.
Example:
```
Files::make('Guideline', 'articles')
                ->singleMediaRules(['mimes:png,jpg,jpeg'])
```

**Comment by ebess** [comment]
Ty @fenestron.

**Comment by xoco70** [comment]
Should it be possible to grey out non complients files when selecting ? 

This is done with the Laravel Nova File type method: `->acceptedTypes('.pdf')` Is there any equivalent ?
