### ISSUE TITLE
custom button text

### ISSUE THREAD

**Issue by atmediauk** [ebess/advanced-nova-media-library#96]
Hello,

Is it possible to specify custom button text for image and file uploads. The current text is "Add New Media" and "Add New File".

**Comment by loveyuxiao** [comment]
resources\lang\vendor\nova\en.json 
  "Add New Media": "Add New ObjectXXX",
  "Add New File": "Add New ObjectXXX",

**Comment by atmediauk** [comment]
@loveyuxiao Perfect, did not know this. Thanks
