### ISSUE TITLE
add custom headers

### ISSUE THREAD

**Issue by pehbehbeh** [ebess/advanced-nova-media-library#98]
It would be great, to be able to add custom headers per field.

It can be used like this with laravel-medialibrary to make files public in a private S3 bucket for example:

```php
$model->addMedia($file)
    ->addCustomHeaders([
        'ACL' => 'public-read'
    ])
    ->toMediaCollection($type);
```

see https://github.com/spatie/laravel-medialibrary/issues/241#issuecomment-349455094

Maybe something like this:

```php
Files::make('Multiple files', 'multiple_files')
    ->customHeaders([
        'ACL' => 'public-read'
    ]);
```

Or did I miss something in the documentation?

**Comment by ebess** [comment]
*Merged* Ty
