### ISSUE TITLE
Not possible to add Media Library fieldtype to page

### ISSUE THREAD

**Issue by marzsman** [ebess/advanced-nova-media-library#99]
I want to use a media field on my page ([Advanced Nova Media Library](https://novapackages.com/packages/ebess/advanced-nova-media-library) ) but because it's using Spatie Media library and the media assets are always assigned to a Model this is not possible.

Is there anyway I could get this to work or can anyone recommend me another Fieldtype for adding multiple images to a page.

This is the error I get

`Argument 1 passed to Spatie\\MediaLibrary\\FileAdder\\FileAdderFactory::create() must be an instance of Illuminate\\Database\\Eloquent\\Model, instance of App\\Nova\\Templates\\About given, called in /Users/maarten/DigitalEvidence/Madbikes/madbikes/vendor/spatie/laravel-medialibrary/src/HasMedia/HasMediaTrait.php on line 73`

**Comment by ebess** [comment]
Hey @marzsman . This packages supports the[ laravel medialibrary ](https://docs.spatie.be/laravel-medialibrary/v7/introduction/)for the nova package. This package does not work as a standalone solution. Maybe you can find something which suits your needs best right here: https://novapackages.com/#images
